#%RAML 1.0
version: 1.0
title: Empdata
types:
  emptype: !include Datatype/empdataType.raml
/employee:
  /{id}:
    get:
     responses:
        200:
          body:
            application/json:
              type: emptype
              example: !include Example/empexample.json
  get:
    responses:
      200:
        body:
          application/json:
            type: emptype
            example: !include Example/empexample.json

  /create:
   post:
    body:
      application/json:
        type: emptype
        example: !include Example/empexample.json
    responses:
      201:
        body:
          application/json:
            example: "Data created!"
  /update/{id}:
   put:
     body:
       application/json:
         type: emptype
         example: !include Example/empexample.json
     responses:
      201:
        body:
          application/json:
            example: "Data updated"
  /delete/{id}:
  delete:
    body:
      application/json:
    responses:
      200:
        body:
          application/json:
            example: "Data deleted"
  
    

              
    
              